"""Render an already computed profile report. No trace parsing or GPU work here."""

import collections
import statistics


def mean_over(stages, path_fn):
    vals = [path_fn(s) for s in stages.values()]
    return statistics.fmean(vals)


def render_md(res, top_n=15):
    st = res["stages"]
    names = list(st)
    n = len(names)
    lines = [f"# Kernel breakdown: `{res['stage_regex']}`", "",
             f"Trace: `{res['trace']}`" + (f" (generation {res['generation']})" if "generation" in res else "")
             + ". Generated by `scripts/analyze_profile.py`; method in its docstring.",
             "Times are GPU kernel durations in ms; shares are of summed kernel time.", "",
             "## Per stage", "",
             "| Stage | GPU span | Busy | Idle | Kernels | Median kernel (µs) | Kernels < 10 µs |",
             "|---|---|---|---|---|---|---|"]
    for k in names:
        s = st[k]
        lines.append(f"| {k} | {s['span_ms']:.1f} | {s['busy_ms']:.1f} | {s['idle_ms']:.1f} | {s['n_kernels']} | "
                     f"{s['median_kernel_us']:.1f} | {100 * s['frac_kernels_under_10us']:.0f}% "
                     f"({s['time_in_kernels_under_10us_ms']:.1f} ms) |")

    if any("osrt_coverage" in s for s in st.values()):
        lines += ["", "## Captured GPU / read-call coverage", "",
                  "Intervals are restricted to the generating process and clipped to each stage.",
                  "Read-only means inside captured read/pread64 calls with no captured GPU activity; it is not measured storage wait.",
                  "Neither is unexplained by these activities, not necessarily idle. OSRT thresholds can omit short calls.", "",
                  "| Stage | Stage span (ms) | GPU-covered (ms) | Read-only-covered (ms) | Neither-covered (ms) |",
                  "|---|---|---|---|---|"]
        for name, stage in st.items():
            if "osrt_coverage" in stage:
                c = stage["osrt_coverage"]
                lines.append(f"| {name} | {stage['span_ms']:.3f} | {c['gpu_covered_ms']:.3f} | "
                             f"{c['read_only_covered_ms']:.3f} | {c['neither_covered_ms']:.3f} |")

    def table(title, key):
        allk = collections.OrderedDict()
        for k in names:
            for g in st[k][key]:
                allk.setdefault(g, None)
        total = mean_over(st, lambda s: s["kernel_sum_ms"])
        rows = []
        for g in allk:
            per = [st[k][key].get(g, {"ms": 0.0, "kernels": 0}) for k in names]
            ms = statistics.fmean(p["ms"] for p in per)
            kern = statistics.fmean(p["kernels"] for p in per)
            rows.append((ms, g, kern, [p["ms"] for p in per]))
        rows.sort(reverse=True)
        out = ["", f"## {title} (mean per stage over {n} stages)", "",
               "| Group | ms / stage | Share | Kernels / stage | " + " | ".join(names) + " |",
               "|---|---|---|---|" + "---|" * n]
        for ms, g, kern, per in rows[:top_n]:
            out.append(f"| `{g}` | {ms:.2f} | {100 * ms / total:.1f}% | {kern:.0f} | "
                       + " | ".join(f"{p:.2f}" for p in per) + " |")
        if len(rows) > top_n:
            rest = sum(r[0] for r in rows[top_n:])
            out.append(f"| (other {len(rows) - top_n}) | {rest:.2f} | {100 * rest / total:.1f}% | | " + " | " * (n - 1) + " |")
        return out

    lines += table("By kernel group", "by_group")
    lines += table("By top-level aten op", "by_top_op")
    lines += table("By leaf aten op (the op that launched the kernel)", "by_leaf_op")

    for title, key in (("GEMM shapes", "gemm_shapes"), ("Attention shapes", "attention_shapes")):
        first = st[names[0]][key]
        if not first:
            continue
        lines += ["", f"## {title} (first stage: `{names[0]}`)", "",
                  "| Shape | ms | Calls | Achieved TFLOP/s |", "|---|---|---|---|"]
        for shape, v in list(first.items())[:top_n]:
            tf = f"{v['tflops']:.0f}" if v["tflops"] else "–"
            lines.append(f"| {shape} | {v['ms']:.2f} | {v['calls']} | {tf} |")
    return "\n".join(lines) + "\n"
